#!/bin/bash

usage() {
  echo "Usage: $(basename ${0}) HOSTNAME"
}

if [[ ${#} -ne 1 ]]; then
  usage
  exit 1
fi

if [[ ! -x $(which host) ]];then
  echo 'host command not found.' 1>&2
  exit 1
fi

host -c chaos -t txt version.bind ${1}

