#!/usr/bin/python

import argparse
import datetime

parser = argparse.ArgumentParser()
parser.add_argument('days', type=int, help='delta in days')
parser.add_argument('base', help='base date in YYYY-MM-DD')
args = parser.parse_args()

def daysafter(daysafter, date):
  tokens = date.split('-')
  y, m, d = [int(s) for s in tokens]
  return datetime.date(y, m, d) + datetime.timedelta(days=daysafter)

print(daysafter(args.days, args.base))

