#!/usr/bin/python
# -*- coding: utf-8 -*-

"""Runs pylint and print formatted output for flymake.

This script is meant to be executed by flymake in Emacs.
cf. http://www.emacswiki.org/emacs/PythonMode
"""

import re
import shlex
import subprocess
import sys

def main():
  commandline = 'pylint -f parseable -r n -d C,R %s' % sys.argv[1]
  proc = subprocess.Popen(shlex.split(commandline), stdout=subprocess.PIPE)
  (stdout, unused_stderr) = proc.communicate()

  for line in stdout.splitlines():
    match = re.search('\\[([WE])(, (.+?))?\\]', line)
    if match:
      kind = match.group(1)
      func = match.group(3)

      if kind == 'W':
        msg = 'Warning'
      else:
        msg = 'Error'

      if func:
        line = re.sub('\\[([WE])(, (.+?))?\\]', '%s (%s):' % (msg, func), line)
      else:
        line = re.sub('\\[([WE])?\\]', '%s:' % msg, line)
    print line

if __name__ == '__main__':
  main()

