#!/usr/bin/python

"""Calculate monthly total bandwidth usage from a report in CSV format.

Format is as follow:
"Category","In Bytes","Out Bytes"
"2009-12-01 00:45:00","116736","0"
"2009-12-01 00:50:00","0","3072000"
"2009-12-01 01:05:00","655362","0"
"2009-12-01 01:15:00","0","3072000"
"2009-12-01 01:30:00","81920","0"
"2009-12-01 01:55:00","0","81920"
"2009-12-01 02:00:00","430082","3072000"
...
...
"""

import sys
from optparse import OptionParser


def main():
  usage = 'usage: %s reportfile.csv' % sys.argv[0]
  parser = OptionParser(usage=usage)
  (unused_options, args) = parser.parse_args()
  if len(args) != 1:
    parser.error('one argument, no more, no less.')
  csv_filename = args[0]
  csv_file = open(csv_filename)
  # header on the first line
  csv_file.readline()
  in_total_bytes = 0
  out_total_bytes = 0
  for line in csv_file:
    items = line.split(',')
    timestamp = items[0]
    in_bytes = int(items[1].replace('"',''))
    out_bytes = int(items[2].replace('"',''))
    in_total_bytes += in_bytes
    out_total_bytes += out_bytes
  print 'in_total_bytes: %.02f MB' % (in_total_bytes / 1024.0 / 1024.0)
  print 'out_total_bytes: %.02f MB' % (out_total_bytes / 1024.0 / 1024.0)


if __name__ == '__main__':
  main()

