#!/bin/bash
# vacuum sqlite used by firefox

case $(uname -s) in
  Linux)
    PROFILE_DIR_PATH="${HOME}/.mozilla/firefox/"
  ;;
  Darwin)
    PROFILE_DIR_PATH="${HOME}/Library/Application Support/Firefox/Profiles/"
    #CACHE_DIR_PATH="${HOME}/Library/Caches/Firefox/Profiles/"
  ;;
  *)
    echo 'unknown architecture'
    exit 1
  ;;
esac

if [[ ! -x $(which sqlite3) ]]; then
  echo 'sqlite3 not found.'
  exit 1
fi

ps -ef | grep firefox-bin | grep -v grep > /dev/null
if [[ ${?} -eq 0 ]]; then
  echo 'firefox seems to be running. bailing out.'
  exit 1
fi

cd "${PROFILE_DIR_PATH}"
for db in */*.sqlite; do
  echo -n 'vacuuming '
  echo ${db}
  sqlite3 ${db} 'VACUUM;'
done
